

pub struct ApiEvent{
    pub id:u128,
    pub series_id:u128,
    pub author_id:u128,
    pub title:String,
    pub description:String,
    pub location:String,
    pub start_time:i64,
    pub end_time:i64,
    pub participants: Vec<String>,
    pub importance_level:String,
    pub repeat_every_n_days:u8,
    pub repeat_every_day:bool,
    pub repeat_every_week:bool,
    pub repeat_every_month:bool,
    pub repeat_every_year:bool,
    pub avoid_holiday:bool,
    pub avoid_weekend:bool,
    pub only_holiday:bool,
    pub only_weekend:bool,
    pub start_date: i64,
    pub stop_date:i64,
    pub stop_times:u8,
    pub skip_if_conflict:bool
}

pub struct ApiReminder{
    pub id:u128,
    pub title:String,
    pub time:i64,
    pub is_done:bool,
    pub is_whole_day:bool,
    pub importance_level:String,
    pub repeat_every_n_days:u8,
    pub repeat_every_day:bool,
    pub repeat_every_week:bool,
    pub repeat_every_month:bool,
    pub repeat_every_year:bool,
    pub avoid_holiday:bool,
    pub avoid_weekend:bool,
    pub only_holiday:bool,
    pub only_weekend:bool,
    pub start_date: i64,
    pub stop_date:i64,
    pub stop_times:u8,
}

pub struct ApiCustomInformation{
    pub id:u128,
    pub name:String,
    pub gender:String,
    pub birthday:i64,
    pub favorite_color:String,
    pub prefer_time:String,
    pub available_time_duration:(i64,i64),
    pub event_count_in_last_week:u8,
    pub event_count_in_last_month:u8,
    pub event_count_in_last_year:u8,
    pub event_count_in_whole_time:u8,
    pub importance_count:(u8,u8,u8,u8,u8),
    pub most_repeat_event_id:u128,
    pub longest_event_id:u128,
}